USE [master]
GO

/****** Object:  Database [PatrocinioZoneDB]    Script Date: 11/24/2024 9:14:27 PM ******/
CREATE DATABASE [PatrocinioZoneDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PatrocinioZoneDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\PatrocinioZoneDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PatrocinioZoneDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\PatrocinioZoneDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PatrocinioZoneDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PatrocinioZoneDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PatrocinioZoneDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PatrocinioZoneDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PatrocinioZoneDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PatrocinioZoneDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PatrocinioZoneDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PatrocinioZoneDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PatrocinioZoneDB] SET  MULTI_USER 
GO

ALTER DATABASE [PatrocinioZoneDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PatrocinioZoneDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PatrocinioZoneDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PatrocinioZoneDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PatrocinioZoneDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PatrocinioZoneDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PatrocinioZoneDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PatrocinioZoneDB] SET  READ_WRITE 
GO

